import type { AtsPlatform } from "../shared/types";
import { seedCompanies } from "../shared/db";

type SeedEntry = { slug: string; name: string; ats: AtsPlatform };

const ASHBY_SEED: SeedEntry[] = [
  { slug: "linear", name: "Linear", ats: "ashby" },
  { slug: "ramp", name: "Ramp", ats: "ashby" },
  { slug: "notion", name: "Notion", ats: "ashby" },
  { slug: "openai", name: "OpenAI", ats: "ashby" },
  { slug: "cursor", name: "Cursor", ats: "ashby" },
  { slug: "vercel", name: "Vercel", ats: "ashby" },
  { slug: "posthog", name: "PostHog", ats: "ashby" },
  { slug: "figma", name: "Figma", ats: "ashby" },
  { slug: "deel", name: "Deel", ats: "ashby" },
  { slug: "lindy", name: "Lindy", ats: "ashby" },
  { slug: "mintlify", name: "Mintlify", ats: "ashby" },
  { slug: "highlight", name: "Highlight", ats: "ashby" },
  { slug: "cal", name: "Cal.com", ats: "ashby" },
  { slug: "tldraw", name: "tldraw", ats: "ashby" },
  { slug: "liveblocks", name: "Liveblocks", ats: "ashby" },
  { slug: "reactionic", name: "Reactionic", ats: "ashby" },
  { slug: "dub", name: "Dub", ats: "ashby" },
  { slug: "percy", name: "Percy", ats: "ashby" },
  { slug: "courier", name: "Courier", ats: "ashby" },
  { slug: "modular", name: "Modular", ats: "ashby" },
  { slug: "anthropic", name: "Anthropic", ats: "ashby" },
  { slug: "retool", name: "Retool", ats: "ashby" },
  { slug: "supabase", name: "Supabase", ats: "ashby" },
  { slug: "snaplet", name: "Snaplet", ats: "ashby" },
  { slug: "neondatabase", name: "Neon", ats: "ashby" },
  { slug: "prisma", name: "Prisma", ats: "ashby" },
  { slug: "trpc", name: "tRPC", ats: "ashby" },
  { slug: "upstash", name: "Upstash", ats: "ashby" },
  { slug: "inch", name: "Inch", ats: "ashby" },
  { slug: "godot", name: "Godot", ats: "ashby" },
  { slug: "deno", name: "Deno", ats: "ashby" },
  { slug: "sanity", name: "Sanity", ats: "ashby" },
  { slug: "workos", name: "WorkOS", ats: "ashby" },
  { slug: "raycast", name: "Raycast", ats: "ashby" },
  { slug: "deepgram", name: "Deepgram", ats: "ashby" },
  { slug: "loops", name: "Loops", ats: "ashby" },
  { slug: "buttondown", name: "Buttondown", ats: "ashby" },
  { slug: "convex", name: "Convex", ats: "ashby" },
  { slug: "trigger", name: "Trigger.dev", ats: "ashby" },
  { slug: "inngest", name: "Inngest", ats: "ashby" },
  { slug: "fly", name: "Fly.io", ats: "ashby" },
  { slug: "mercury", name: "Mercury", ats: "ashby" },
  { slug: "lattice", name: "Lattice", ats: "ashby" },
  { slug: "height", name: "Height", ats: "ashby" },
  { slug: "rows", name: "Rows", ats: "ashby" },
  { slug: "reflect", name: "Reflect", ats: "ashby" },
  { slug: "readwise", name: "Readwise", ats: "ashby" },
  { slug: "convertkit", name: "ConvertKit", ats: "ashby" },
  { slug: "fathom", name: "Fathom", ats: "ashby" },
  { slug: "plausible", name: "Plausible", ats: "ashby" },
  { slug: "1password", name: "1Password", ats: "ashby" },
  { slug: "airtable", name: "Airtable", ats: "ashby" },
  { slug: "airwallex", name: "Airwallex", ats: "ashby" },
  { slug: "alan", name: "Alan", ats: "ashby" },
  { slug: "andela", name: "Andela", ats: "ashby" },
  { slug: "Ashby", name: "Ashby", ats: "ashby" },
  { slug: "astral", name: "Astral", ats: "ashby" },
  { slug: "aurorasolar", name: "Aurora Solar", ats: "ashby" },
  { slug: "babbel", name: "Babbel", ats: "ashby" },
  { slug: "benchling", name: "Benchling", ats: "ashby" },
  { slug: "benepass", name: "Benepass", ats: "ashby" },
  { slug: "bestow", name: "Bestow", ats: "ashby" },
  { slug: "boomi", name: "Boomi", ats: "ashby" },
  { slug: "brightline", name: "Brightline", ats: "ashby" },
  { slug: "calm", name: "Calm", ats: "ashby" },
  { slug: "character", name: "Character.AI", ats: "ashby" },
  { slug: "checkout", name: "Checkout.com", ats: "ashby" },
  { slug: "clay", name: "Clay", ats: "ashby" },
  { slug: "coder", name: "Coder", ats: "ashby" },
  { slug: "cognition", name: "Cognition", ats: "ashby" },
  { slug: "cohere", name: "Cohere", ats: "ashby" },
  { slug: "cointracker", name: "CoinTracker", ats: "ashby" },
  { slug: "commonroom", name: "Common Room", ats: "ashby" },
  { slug: "crusoe", name: "Crusoe", ats: "ashby" },
  { slug: "cryptio", name: "Cryptio", ats: "ashby" },
  { slug: "dave", name: "Dave", ats: "ashby" },
  { slug: "decimal", name: "Decimal", ats: "ashby" },
  { slug: "deliveroo", name: "Deliveroo", ats: "ashby" },
  { slug: "docker", name: "Docker", ats: "ashby" },
  { slug: "duolingo", name: "Duolingo", ats: "ashby" },
  { slug: "eightsleep", name: "EightSleep", ats: "ashby" },
  { slug: "enpal", name: "Enpal", ats: "ashby" },
  { slug: "exa", name: "Exa", ats: "ashby" },
  { slug: "flocksafety", name: "Flock Safety", ats: "ashby" },
  { slug: "formenergy", name: "Form Energy", ats: "ashby" },
  { slug: "frontcareers", name: "Front", ats: "ashby" },
  { slug: "fullstory", name: "FullStory", ats: "ashby" },
  { slug: "gamechanger", name: "GameChanger", ats: "ashby" },
  { slug: "gen-digital", name: "Gen Digital", ats: "ashby" },
  { slug: "go-augment", name: "Augment", ats: "ashby" },
  { slug: "hackerone", name: "HackerOne", ats: "ashby" },
  { slug: "harvey", name: "Harvey", ats: "ashby" },
  { slug: "helpscout", name: "Help Scout", ats: "ashby" },
  { slug: "hopper", name: "Hopper", ats: "ashby" },
  { slug: "illumio", name: "Illumio", ats: "ashby" },
  { slug: "incidentio", name: "incident.io", ats: "ashby" },
  { slug: "instructure", name: "Instructure", ats: "ashby" },
  { slug: "ironclad", name: "Ironclad", ats: "ashby" },
  { slug: "junipersquare", name: "Juniper Square", ats: "ashby" },
  { slug: "klue", name: "Klue", ats: "ashby" },
  { slug: "langfuse", name: "Langfuse", ats: "ashby" },
  { slug: "leapsome", name: "Leapsome", ats: "ashby" },
  { slug: "ledger", name: "Ledger", ats: "ashby" },
  { slug: "lemonade", name: "Lemonade", ats: "ashby" },
  { slug: "lightspeed-commerce", name: "Lightspeed Commerce", ats: "ashby" },
  { slug: "lime", name: "Lime", ats: "ashby" },
  { slug: "lumaai", name: "Luma AI", ats: "ashby" },
  { slug: "marqeta", name: "Marqeta", ats: "ashby" },
  { slug: "marshmallow", name: "Marshmallow", ats: "ashby" },
  { slug: "mazedesign", name: "Maze", ats: "ashby" },
  { slug: "moderntreasury", name: "Modern Treasury", ats: "ashby" },
  { slug: "montecarlodata", name: "Monte Carlo", ats: "ashby" },
  { slug: "mparticle", name: "mParticle", ats: "ashby" },
  { slug: "multiverse", name: "Multiverse", ats: "ashby" },
  { slug: "mural", name: "Mural", ats: "ashby" },
  { slug: "mystenlabs", name: "Mysten Labs", ats: "ashby" },
  { slug: "nango", name: "Nango", ats: "ashby" },
  { slug: "netgear", name: "NETGEAR", ats: "ashby" },
  { slug: "nivoda", name: "Nivoda", ats: "ashby" },
  { slug: "opendoor", name: "Opendoor", ats: "ashby" },
  { slug: "openrouter", name: "OpenRouter", ats: "ashby" },
  { slug: "oyster", name: "Oyster", ats: "ashby" },
  { slug: "patreon", name: "Patreon", ats: "ashby" },
  { slug: "pennylane", name: "Pennylane", ats: "ashby" },
  { slug: "permitflow", name: "PermitFlow", ats: "ashby" },
  { slug: "perplexity", name: "Perplexity", ats: "ashby" },
  { slug: "plaid", name: "Plaid", ats: "ashby" },
  { slug: "polymarket", name: "Polymarket", ats: "ashby" },
  { slug: "pylon-labs", name: "Pylon", ats: "ashby" },
  { slug: "quora", name: "Quora", ats: "ashby" },
  { slug: "radai", name: "Rad AI", ats: "ashby" },
  { slug: "reddit", name: "Reddit", ats: "ashby" },
  { slug: "reflectionai", name: "Reflection AI", ats: "ashby" },
  { slug: "replit", name: "Replit", ats: "ashby" },
  { slug: "replo", name: "Replo", ats: "ashby" },
  { slug: "revenuecat", name: "RevenueCat", ats: "ashby" },
  { slug: "rula", name: "Rula", ats: "ashby" },
  { slug: "saronic", name: "Saronic Technologies", ats: "ashby" },
  { slug: "scribehow", name: "Scribe", ats: "ashby" },
  { slug: "semgrep", name: "Semgrep", ats: "ashby" },
  { slug: "sequoia", name: "Sequoia", ats: "ashby" },
  { slug: "sfcompute", name: "SF Compute", ats: "ashby" },
  { slug: "socure", name: "Socure", ats: "ashby" },
  { slug: "solanafoundation", name: "Solana Foundation", ats: "ashby" },
  { slug: "stytch", name: "Stytch", ats: "ashby" },
  { slug: "suno", name: "Suno", ats: "ashby" },
  { slug: "superhuman", name: "Superhuman", ats: "ashby" },
  { slug: "taktile", name: "Taktile", ats: "ashby" },
  { slug: "teal", name: "Teal", ats: "ashby" },
  { slug: "tennr", name: "Tennr", ats: "ashby" },
  { slug: "theydo", name: "TheyDo", ats: "ashby" },
  { slug: "trainline", name: "Trainline", ats: "ashby" },
  { slug: "uipath", name: "UiPath", ats: "ashby" },
  { slug: "wetransfer", name: "WeTransfer", ats: "ashby" },
  { slug: "whatnot", name: "Whatnot", ats: "ashby" },
  { slug: "workiva", name: "Workiva", ats: "ashby" },
  { slug: "workweave", name: "Weave", ats: "ashby" },
  { slug: "writer", name: "Writer", ats: "ashby" },
  { slug: "zello", name: "Zello", ats: "ashby" },
];

const GREENHOUSE_SEED: SeedEntry[] = [
  { slug: "stripe", name: "Stripe", ats: "greenhouse" },
  { slug: "airbnb", name: "Airbnb", ats: "greenhouse" },
  { slug: "discord", name: "Discord", ats: "greenhouse" },
  { slug: "cloudflare", name: "Cloudflare", ats: "greenhouse" },
  { slug: "zapier", name: "Zapier", ats: "greenhouse" },
  { slug: "gitlab", name: "GitLab", ats: "greenhouse" },
  { slug: "hashicorp", name: "HashiCorp", ats: "greenhouse" },
  { slug: "gitguardian", name: "GitGuardian", ats: "greenhouse" },
  { slug: "ghost", name: "Ghost", ats: "greenhouse" },
  { slug: "netlify", name: "Netlify", ats: "greenhouse" },
  { slug: "datadog", name: "Datadog", ats: "greenhouse" },
  { slug: "algolia", name: "Algolia", ats: "greenhouse" },
  { slug: "contentful", name: "Contentful", ats: "greenhouse" },
  { slug: "hasura", name: "Hasura", ats: "greenhouse" },
  { slug: "nhost", name: "Nhost", ats: "greenhouse" },
  { slug: "render", name: "Render", ats: "greenhouse" },
  { slug: "pinpoint", name: "Pinpoint", ats: "greenhouse" },
  { slug: "jumpcloud", name: "JumpCloud", ats: "greenhouse" },
  { slug: "dbt-labs", name: "dbt Labs", ats: "greenhouse" },
  { slug: "airbyte", name: "Airbyte", ats: "greenhouse" },
  { slug: "fivetran", name: "Fivetran", ats: "greenhouse" },
  { slug: "cockroachdb", name: "CockroachDB", ats: "greenhouse" },
  { slug: "cockroachlabs", name: "Cockroach Labs", ats: "greenhouse" },
  { slug: "timescale", name: "Timescale", ats: "greenhouse" },
  { slug: "materialize", name: "Materialize", ats: "greenhouse" },
  { slug: "replicated", name: "Replicated", ats: "greenhouse" },
  { slug: "buildkite", name: "Buildkite", ats: "greenhouse" },
  { slug: "flywire", name: "Flywire", ats: "greenhouse" },
  { slug: "gorgias", name: "Gorgias", ats: "greenhouse" },
  { slug: "front", name: "Front", ats: "greenhouse" },
  { slug: "intercom", name: "Intercom", ats: "greenhouse" },
  { slug: "webflow", name: "Webflow", ats: "greenhouse" },
  { slug: "databricks", name: "Databricks", ats: "greenhouse" },
  { slug: "confluent", name: "Confluent", ats: "greenhouse" },
  { slug: "mongodb", name: "MongoDB", ats: "greenhouse" },
  { slug: "elastic", name: "Elastic", ats: "greenhouse" },
  { slug: "snowflake", name: "Snowflake", ats: "greenhouse" },
  { slug: "grafana", name: "Grafana", ats: "greenhouse" },
  { slug: "clickhouse", name: "ClickHouse", ats: "greenhouse" },
  { slug: "getsentry", name: "Sentry", ats: "greenhouse" },
  { slug: "raygun", name: "Raygun", ats: "greenhouse" },
  { slug: "ably", name: "Ably", ats: "greenhouse" },
  { slug: "pusher", name: "Pusher", ats: "greenhouse" },
  { slug: "messagebird", name: "MessageBird", ats: "greenhouse" },
  { slug: "twilio", name: "Twilio", ats: "greenhouse" },
  { slug: "segment", name: "Segment", ats: "greenhouse" },
  { slug: "mixpanel", name: "Mixpanel", ats: "greenhouse" },
  { slug: "amplitude", name: "Amplitude", ats: "greenhouse" },
  { slug: "vanta", name: "Vanta", ats: "greenhouse" },
  { slug: "drata", name: "Drata", ats: "greenhouse" },
];

const LEVER_SEED: SeedEntry[] = [
  { slug: "netflix", name: "Netflix", ats: "lever" },
  { slug: "shopify", name: "Shopify", ats: "lever" },
  { slug: "databricks", name: "Databricks", ats: "lever" },
  { slug: "unity", name: "Unity", ats: "lever" },
  { slug: "upstart", name: "Upstart", ats: "lever" },
  { slug: "nubank", name: "Nubank", ats: "lever" },
  { slug: "ripple", name: "Ripple", ats: "lever" },
  { slug: "coinbase", name: "Coinbase", ats: "lever" },
  { slug: "clearbit", name: "Clearbit", ats: "lever" },
  { slug: "hover", name: "Hover", ats: "lever" },
  { slug: "lendup", name: "LendUp", ats: "lever" },
  { slug: "kalepa", name: "Kalepa", ats: "lever" },
  { slug: "scale", name: "Scale AI", ats: "lever" },
  { slug: "brex", name: "Brex", ats: "lever" },
  { slug: "coda", name: "Coda", ats: "lever" },
  { slug: "dropbox", name: "Dropbox", ats: "lever" },
  { slug: "asana", name: "Asana", ats: "lever" },
  { slug: "transmit", name: "Transmit", ats: "lever" },
  { slug: "pagerduty", name: "PagerDuty", ats: "lever" },
  { slug: "lob", name: "Lob", ats: "lever" },
  { slug: "betterment", name: "Betterment", ats: "lever" },
  { slug: "gusto", name: "Gusto", ats: "lever" },
  { slug: "notarize", name: "Notarize", ats: "lever" },
  { slug: "flyhomes", name: "FlyHomes", ats: "lever" },
  { slug: "dialpad", name: "Dialpad", ats: "lever" },
  { slug: "talkdesk", name: "Talkdesk", ats: "lever" },
  { slug: "segment", name: "Segment", ats: "lever" },
  { slug: "tray", name: "Tray.io", ats: "lever" },
  { slug: "workato", name: "Workato", ats: "lever" },
  { slug: "zapier", name: "Zapier", ats: "lever" },
];

export function runSeed(): number {
  const all = [...ASHBY_SEED, ...GREENHOUSE_SEED, ...LEVER_SEED];
  const added = seedCompanies(all);
  console.log(`[seed] ${added} new companies seeded (${all.length} total in list)`);
  return added;
}
