import { Module } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";
import {
  Company,
  Job,
  JobFilterEntity,
  Application,
  ApplicationRun,
  ApplicationRunStep,
  JobDocument,
  SearchConfigEntity,
  TaskRun,
  TaskRunLog,
  UserProfile,
  UserAnswer,
  CompanySnapshot,
} from "../entities";
import {
  CompaniesRepository,
  JobsRepository,
  JobFiltersRepository,
  JobDocumentsRepository,
  TaskRunsRepository,
  TaskRunLogsRepository,
  ApplicationsRepository,
  ApplicationRunsRepository,
  ApplicationRunStepsRepository,
  UserProfileRepository,
  UserAnswersRepository,
  SearchConfigRepository,
  ShortlistRepository,
  CompanySnapshotsRepository,
} from "./index";

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Company,
      Job,
      JobFilterEntity,
      Application,
      ApplicationRun,
      ApplicationRunStep,
      JobDocument,
      SearchConfigEntity,
      TaskRun,
      TaskRunLog,
      UserProfile,
      UserAnswer,
      CompanySnapshot,
    ]),
  ],
  providers: [
    CompaniesRepository,
    JobsRepository,
    JobFiltersRepository,
    JobDocumentsRepository,
    TaskRunsRepository,
    TaskRunLogsRepository,
    ApplicationsRepository,
    ApplicationRunsRepository,
    ApplicationRunStepsRepository,
    UserProfileRepository,
    UserAnswersRepository,
    SearchConfigRepository,
    ShortlistRepository,
    CompanySnapshotsRepository,
  ],
  exports: [
    CompaniesRepository,
    JobsRepository,
    JobFiltersRepository,
    JobDocumentsRepository,
    TaskRunsRepository,
    TaskRunLogsRepository,
    ApplicationsRepository,
    ApplicationRunsRepository,
    ApplicationRunStepsRepository,
    UserProfileRepository,
    UserAnswersRepository,
    SearchConfigRepository,
    ShortlistRepository,
    CompanySnapshotsRepository,
  ],
})
export class RepositoriesModule {}
